export const jobs=[
  {
    title: "Ethiopian Airlines Vacancy Par-Time Instructors",
    url: "https://effoysira.com/ethiopian-airlines-vacancy-par-time-instructors/",
    date: "SEPTEMBER 19, 2023",
    from: "EFFOY",
    desc: "Ethiopian Airlines Group would like to announce a new vacant position in the capacity of Par-Time Instructors. Position 1: Par-Time Instructor- Engineering Drawing I QUALIFICATION REQUIREMENTS: Ph.D. degree in engineering or a related field, and relevant experience in engineering graphics and…",
  },
  {
    title: "Coca Cola Job Vacancy Sept 2023",
    url: "https://effoysira.com/coca-cola-job-vacancy-sept-2023/",
    date: "SEPTEMBER 19, 2023",
    from: "EFFOY",
    desc: "East Africa Bottling Share Company ( EABSC) works with the world’s most cherished trademark; invests in the most sophisticated production system in the world and employ people who are prepared to work with passion and focus. East Africa Bottling SC…",
  },
  {
    title: "Neo Microfinance Job Vacancy 2023",
    url: "https://effoysira.com/neo-microfinance-job-vacancy-2023/",
    date: "SEPTEMBER 19, 2023",
    from: "EFFOY",
    desc: "Neo Microfinance Institution S.C invite interested and qualified applicants for the following job positions. NEO Microfinance, “NEO”, is an Ethiopian Microfinance Institution (MFI) under formation that has fulfilled all the prerequisites of the National Bank of Ethiopia’s regulatory requirements necessary…",
  },
  {
    title: "Ethiopian Railways Corporation Vacancy 2023",
    url: "https://effoysira.com/ethiopian-railways-corporation-vacancy-2023/",
    date: "SEPTEMBER 19, 2023",
    from: "EFFOY",
    desc: "Ethiopian Railways Corporation invites Fresh graduates and qualified candidates for the following positions. Ethiopian Railway, commonly known as ER, full name Ethiopian Railway Corporation, is the national railway operator of the Federal Democratic Republic of Ethiopia, under the regulation of…",
  },
  {
    title: "Jobs by Saudia Arabian Airlines",
    url: "https://effoysira.com/jobs-by-saudia-arabian-airlines/",
    date: "SEPTEMBER 18, 2023",
    from: "EFFOY",
    desc: "Saudia Arabian Airlines Job Vacancy 2023, Saudia Arabian Airlines. SAUDIA is the first founded airline in the Arabian peninsula. It started in 1945 with one DC-3, and since then it has marched forward towards excellence recording the highest level of…",
  },
  {
    title: "Ethiopian Airlines Group Vacancy | Instructor",
    url: "https://effoysira.com/ethiopian-airlines-group-vacancy-instructor/",
    date: "SEPTEMBER 17, 2023",
    from: "EFFOY",
    desc: "Ethiopian Airlines Group would like to announce a new vacant position in the capacity of INSTRUCTOR TECHNICAL – NAVIGATION. Ethiopian Airlines (Ethiopian) has had more than 75 years of successful journey which made it the leading Aviation Group in Africa.…",
  },
  {
    title: "Ethiopian Skylight Hotel Vacancy Sept 2023",
    url: "https://effoysira.com/ethiopian-skylight-hotel-vacancy-aug-2023/",
    date: "SEPTEMBER 14, 2023",
    from: "EFFOY",
    desc: "Ethiopian Skylight Hotel invites qualified applicants for the following job position. Ethiopian Skylight Hotel is a striking contemporary property with elegant design and outstanding facilities in a prime location just 5 minutes´ walk away from the Addis Ababa Bole International…",
  },
  {
    title: "Germany Embassy Job Vacancy 2023",
    url: "https://effoysira.com/germany-embassy-job-vacancy-2023/",
    date: "SEPTEMBER 14, 2023",
    from: "EFFOY",
    desc: "The Embassy of the Federal Republic of Germany in Addis Ababa seeks to recruit two suitably qualified candidates for Assistant Clerks Position. Position: Assistant Clerks ( At the Visa and Consular Section ) The applicant should possess the following minimum…",
  },
  {
    title: "British Embassy Vacancy | Internship",
    url: "https://effoysira.com/british-embassy-vacancy-internship/",
    date: "SEPTEMBER 14, 2023",
    from: "EFFOY",
    desc: "The British Government is an inclusive and diversity-friendly employer.  We value difference, promote equality and challenge discrimination, enhancing our organizational capability. We welcome and encourage applications from people of all backgrounds. We do not discriminate on the basis of disability,…",
  },
];
